### ISSUE TITLE
Default config.files.src should be an array

### ISSUE THREAD

**Issue by paul-barry-kenzan** [kenzanlabs/pipeline-test-node#12]
When attempting to pass an array of globs to the pipeline, I get an error: 
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: streams not supported

Process finished with exit code 1
```

I was able to determine that this was because the default `config.files.src` is a simple string, while I'm passing an array. When the pipeline attempts to merge the config objects, it fails. By making the default file path a single item array, I was able to run the pipeline successfully.

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan do you see this is as a bug or an enhancement?  If you submit a PR, i can get this published ASAP for you

**Comment by paul-barry-kenzan** [comment]
It's a bug. I can't use this without making the default an array. PR on its way.

**Comment by obuckley-kenzan** [comment]
Awesome, thanks!
