### ISSUE TITLE
Test configuration can be improved

### ISSUE THREAD

**Issue by franciov** [kenzanlabs/pipeline-test-node#18]
The pipeline requires to be initialised by passing a test configuration like:

```
var testConfig = {
  files: {
    src: [
      './src/*.js',
      './specs/**/*.js'
    ]
  },
  plugins: {
    istanbul: {
      reporters: ['text-summary'],
      thresholds: {
        global: 70
      }
    }
  }
};

var testPipeline = require('pipeline-test-node')(testConfig);
```

This implies that:

- we need to declare the pipeline variable after the configuration
- not sure we have default values for the configuration?
- we need to use the test configuration also in `gulp.src` to avoid duplicating the `files.src`

A better interface would be:

```
const testPipeline = require('pipeline-test-node');
const optionalTestConfiguration = {
  plugins: {
    instanbul: true, // default values
    mocha: false // disabled
  }
};

gulp.task('test', ['lint'], function () {
  return gulp.src([ // define files to test only here if possible (it might be not)
      './src/*.js',
      './specs/**/*.js'
    ], {
    read: false
  })
  .pipe(testPipeline.test(optionalTestConfiguration));
});
```

Thoughts?

**Comment by obuckley-kenzan** [comment]
thanks @franciov .  There's a long standing top-level improvement ticket to capture this for existing projects - https://github.com/kenzanlabs/keystone/issues/7

I will leave this open to capture it specifically for this particular project

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan 
Seems now that we resolved #5 via #25 , the boilerplate associated with using this package is greatly reduced.  we can now simply do something like 
```javascript

var gulp = require('gulp');
var testPipeline = require('pipeline-test-node');
var validatePipeline = require('pipeline-validate-js');

var config = {
  jsFiles: [
    'src/**/*.js',
    'test/**/*.js'
  ]
};

gulp.task('validate', function() {

  return gulp.src(config.jsFiles)
    .pipe(validatePipeline.validateJS())
    .pipe(testPipeline.test());
});
```

and get our desired coverage options, like we can in this Jenkins job
https://kenzan.ci.cloudbees.com/job/CI-pipeline-test-node/

**Comment by paul-barry-kenzan** [comment]
@obuckley-kenzan 
I feel that this issue is irrelevant because of #25

**Comment by obuckley-kenzan** [comment]
Closing as fixing our istanbul configuration has helped clean this up a lot to attain our desired defaults, and plugins can be overridden by following the structure of the underlying plugins themselves.
