### ISSUE TITLE
Should we remove gulp/lazypipe from the internal workings of pipelines?

### ISSUE THREAD

**Issue by paul-barry-kenzan** [kenzanlabs/pipeline-test-node#34]
While updating the version of Mocha and gulp-mocha, I dug into the source of how gulp-mocha utilizes streams internally, specifically for how to unit test pipeline middleware. I noticed that the author, @sindresorhus, uses the `through` library to create a writable stream, rather than using `gulp` under the hood. This method seems to be a cleaner, more isolated means of creating and testing pipelines. 

Here's a reference to the `through` method being used:
https://github.com/sindresorhus/gulp-mocha/blob/master/index.js#L33

And one to the unit tests for that same file:
https://github.com/sindresorhus/gulp-mocha/blob/master/test/test.js

You'll notice that `gulp` is not required in either file, allowing for a generic stream to be created with no dependency on a single task runner. Not sure there's plans on the roadmap to move away from gulp, but by removing the dependency, we make it easier if/when that discussion arises. 

My question is whether we should refactor the Keystone pipelines to utilize [`through`](https://www.npmjs.com/package/through) (or [`through2`](https://www.npmjs.com/package/through2) if that's more suitable) to remove the direct gulp/lazypipe dependency?

**Comment by paul-barry-kenzan** [comment]
Sweet, @bsawyer! I've started kicking around a `through` solution, think I should convert to `through2`?

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan 
Is this a recommendation for all pipelines?  If so, I think we should track as an issue in the "parent" project, Keystone.

**Comment by paul-barry-kenzan** [comment]
@obuckley-kenzan 
Yes, the question was triggered by work on this repo, but should probably be part of the larger convo.

I've created an issue on the parent, closing this one.
https://github.com/kenzanlabs/keystone/issues/35
