### ISSUE TITLE
add stream-assert as a dependency

### ISSUE THREAD

**Issue by obuckley-kenzan** [kenzanlabs/pipeline-test-node#7]
https://github.com/floatdrop/stream-assert

**Comment by obuckley-kenzan** [comment]
I thought this would install it this dependency "top-level" when this pipeline was installed, but don' think this will apply until a later version of npm is used that installs dependencies "flat" like bower does

cc: @csharon

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan  
You've used this package, is this something you've run across?

**Comment by paul-barry-kenzan** [comment]
@obuckley-kenzan 
Sorry, never used that package before. Looks pretty cool though. How do you see this being integrated?

**Comment by obuckley-kenzan** [comment]
must have been late, I guess I'm not clear why this needed then.
